# Generated by Django 5.1.15 on 2025-12-19 18:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('payment', 'Arrecadação'), ('potluck', 'Lanche Partilhado'), ('mixed', 'Misto')], default='payment', max_length=20, verbose_name='Tipo do Evento')),
                ('event_date', models.DateField(verbose_name='Data do Evento')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total esperado para arrecadação', max_digits=10, null=True, verbose_name='Orçamento Total')),
                ('individual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente se não informado', max_digits=10, null=True, verbose_name='Valor por Pessoa')),
                ('pix_key', models.CharField(blank=True, help_text='Chave PIX para recebimento', max_length=100, verbose_name='Chave PIX')),
                ('pix_holder_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Titular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='accounts.guardian', verbose_name='Criado por')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_events', to='accounts.guardian', verbose_name='Responsável pela Arrecadação')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='classes.schoolclass', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('item_type', models.CharField(choices=[('expense', 'Despesa'), ('contribution', 'Contribuição')], default='contribution', max_length=20, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='accounts.guardian', verbose_name='Responsável')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Item do Evento',
                'verbose_name_plural': 'Itens do Evento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('receipt', models.ImageField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Comprovante')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to='accounts.guardian', verbose_name='Confirmado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.event', verbose_name='Evento')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.guardian', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
