# Generated by Django 5.1.15 on 2025-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Endereço ou local onde o evento será realizado', max_length=300, verbose_name='Local do Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, help_text='Link do Google Maps ou similar', verbose_name='Link do Local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Descreva o evento, objetivo e outras informações importantes', verbose_name='Descrição'),
        ),
    ]
