# Generated by Django 5.1.15 on 2025-12-19 19:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0002_event_location_event_location_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('payment', 'Arrecadação'), ('potluck', 'Lanche Partilhado'), ('presence', 'Confirmação de Presença'), ('mixed', 'Misto')], default='payment', max_length=20, verbose_name='Tipo do Evento'),
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('declined', 'Recusado')], default='pending', max_length=20, verbose_name='Status')),
                ('contribution', models.CharField(blank=True, help_text='Ex: Pão de queijo, biscoitos, suco de uva', max_length=300, verbose_name='O que vai levar')),
                ('guests_count', models.PositiveIntegerField(default=1, help_text='Quantas pessoas irão ao evento', verbose_name='Quantidade de pessoas')),
                ('notes', models.TextField(blank=True, help_text='Informações adicionais, restrições alimentares, etc.', verbose_name='Observações')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event', verbose_name='Evento')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='accounts.guardian', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'guardian')},
            },
        ),
    ]
