# Generated by Django 5.1.15 on 2025-12-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type_eventparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Aceita imagens (JPG, PNG) ou PDF', upload_to='receipts/%Y/%m/', verbose_name='Comprovante'),
        ),
    ]
