# Generated by Django 5.1.15 on 2025-12-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='pix_holder_name',
            field=models.CharField(blank=True, help_text='Nome que aparece ao receber PIX', max_length=100, verbose_name='Nome do Titular PIX'),
        ),
    ]
