# Generated by Django 5.1.15 on 2025-12-19 18:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone Material Design', max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Categoria de Fornecedor',
                'verbose_name_plural': 'Categorias de Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Contato')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('instagram', models.CharField(blank=True, help_text='Apenas o usuário, sem @', max_length=100, verbose_name='Instagram')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('description', models.TextField(blank=True, help_text='Serviços oferecidos, especialidades, etc.', verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre o fornecedor', verbose_name='Observações')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Avaliação de 1 a 5 estrelas', null=True, verbose_name='Avaliação')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Recomendado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='suppliers.suppliercategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
    ]
