# Generated by Django 5.1.15 on 2025-12-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='longitude',
        ),
        migrations.AddField(
            model_name='supplier',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Cole o link do Google Maps aqui', verbose_name='Link do Google Maps'),
        ),
    ]
