# Generated by Django 5.1.15 on 2025-12-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_replace_latlong_with_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Ex: Costureira, Decorador, Boleira, Buffet', max_length=100, verbose_name='Categoria'),
        ),
    ]
