# Generated by Django 5.1.15 on 2025-12-19 18:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: 3º Ano A, Maternal II', max_length=100, verbose_name='Nome da Turma')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='Escola')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='Ano Letivo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('invite_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de Convite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassInvitation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Deixe em branco para convite genérico', max_length=254, verbose_name='E-mail do Convidado')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to='accounts.guardian', verbose_name='Aceito por')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='accounts.guardian', verbose_name='Convidado por')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='classes.schoolclass', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Aluno')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('notes', models.TextField(blank=True, help_text='Alergias, restrições alimentares, etc.', verbose_name='Observações')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.guardian', verbose_name='Responsável')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.schoolclass', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Membro')], default='member', max_length=20, verbose_name='Papel')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to='accounts.guardian', verbose_name='Responsável')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='classes.schoolclass', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Membro da Turma',
                'verbose_name_plural': 'Membros da Turma',
                'ordering': ['guardian__user__first_name'],
                'unique_together': {('school_class', 'guardian')},
            },
        ),
    ]
